#!/usr/bin/env ruby
# frozen_string_literal: true

# Example: Monitoring Storage — ActiveRecordAdapter
#
# Demonstrates direct use of DecisionAgent::Monitoring::Storage::ActiveRecordAdapter:
#   1. Setting up the adapter with an in-memory SQLite database
#   2. Recording each metric type
#   3. Querying statistics and time-series data
#   4. Running cleanup with a retention window
#   5. Checking metrics_count

require "bundler/setup"
require "active_record"
require "decision_agent"
require "decision_agent/monitoring/storage/activerecord_adapter"

# ── Database setup ────────────────────────────────────────────────────────────
# In a real Rails app this is handled by `rails g decision_agent:monitoring_migration`
# and `rails db:migrate`. Here we use an in-memory SQLite database so the example
# runs without any external infrastructure.

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil # suppress migration output

ActiveRecord::Schema.define do
  create_table :decision_logs do |t|
    t.string  :decision, null: false
    t.float   :confidence
    t.integer :evaluations_count, default: 0
    t.float   :duration_ms
    t.string  :status
    t.text    :context
    t.text    :metadata
    t.timestamps
  end

  create_table :evaluation_metrics do |t|
    t.references :decision_log, foreign_key: true
    t.string  :evaluator_name, null: false
    t.float   :score
    t.boolean :success
    t.float   :duration_ms
    t.text    :details
    t.timestamps
  end

  create_table :performance_metrics do |t|
    t.string :operation, null: false
    t.float  :duration_ms
    t.string :status
    t.text   :metadata
    t.timestamps
  end

  create_table :error_metrics do |t|
    t.string :error_type, null: false
    t.text   :message
    t.text   :stack_trace
    t.string :severity
    t.text   :context
    t.timestamps
  end
end

# ── Model definitions ─────────────────────────────────────────────────────────
# In a Rails app these live in app/models/ (generated by the migration generator).

class DecisionLog < ActiveRecord::Base
  has_many :evaluation_metrics, dependent: :destroy

  scope :recent, ->(seconds) { where("created_at >= ?", Time.now - seconds) }

  def self.success_rate(time_range: 3600)
    total = recent(time_range).where.not(status: nil).count
    return 0.0 if total.zero?

    recent(time_range).where(status: "success").count.to_f / total
  end
end

class EvaluationMetric < ActiveRecord::Base
  belongs_to :decision_log, optional: true

  scope :recent,     ->(seconds) { where("created_at >= ?", Time.now - seconds) }
  scope :successful, -> { where(success: true) }
end

class PerformanceMetric < ActiveRecord::Base
  scope :recent, ->(seconds) { where("created_at >= ?", Time.now - seconds) }

  def self.average_duration(time_range: 3600)
    recent(time_range).average(:duration_ms).to_f
  end

  def self.percentile(pct, time_range: 3600)
    durations = recent(time_range).where.not(duration_ms: nil).order(:duration_ms).pluck(:duration_ms)
    return 0.0 if durations.empty?

    durations[(durations.length * pct).ceil - 1].to_f
  end

  def self.p50(time_range: 3600) = percentile(0.50, time_range: time_range)
  def self.p95(time_range: 3600) = percentile(0.95, time_range: time_range)
  def self.p99(time_range: 3600) = percentile(0.99, time_range: time_range)

  def self.success_rate(time_range: 3600)
    total = recent(time_range).where.not(status: nil).count
    return 0.0 if total.zero?

    recent(time_range).where(status: "success").count.to_f / total
  end
end

class ErrorMetric < ActiveRecord::Base
  scope :recent,   ->(seconds) { where("created_at >= ?", Time.now - seconds) }
  scope :critical, -> { where(severity: "critical") }
end

# ── Example code ──────────────────────────────────────────────────────────────

puts "=" * 60
puts "DecisionAgent — ActiveRecord Monitoring Adapter"
puts "=" * 60

adapter = DecisionAgent::Monitoring::Storage::ActiveRecordAdapter.new

puts "\n1. Availability check"
puts "   available? => #{DecisionAgent::Monitoring::Storage::ActiveRecordAdapter.available?}"

# ── Record metrics ────────────────────────────────────────────────────────────

puts "\n2. Recording metrics"

10.times do |i|
  adapter.record_decision(
    "loan_approval",
    { applicant_id: 1000 + i, amount: 5000 * (i + 1) },
    confidence:        0.7 + (i * 0.02),
    evaluations_count: 3,
    duration_ms:       20 + (i * 3),
    status:            i.even? ? "success" : "failure"
  )
end

5.times do |i|
  adapter.record_evaluation(
    "CreditScoreEvaluator",
    score:       0.80 + (i * 0.03),
    success:     true,
    duration_ms: 8 + i,
    details:     { bureau: "Experian", score: 650 + (i * 10) }
  )
end

8.times do |i|
  adapter.record_performance(
    "db_query",
    duration_ms: 5 + (i * 2),
    status:      "success",
    metadata:    { table: "applicants" }
  )
end

3.times do |i|
  adapter.record_error(
    "ValidationError",
    message:     "Missing required field: #{%w[income employment assets][i]}",
    severity:    i.zero? ? "critical" : "medium",
    stack_trace: ["lib/validator.rb:#{10 + i}", "lib/agent.rb:42"]
  )
end

puts "   Recorded 10 decisions, 5 evaluations, 8 performance metrics, 3 errors"

# ── metrics_count ─────────────────────────────────────────────────────────────

puts "\n3. Metrics count"
counts = adapter.metrics_count
puts "   decisions:   #{counts[:decisions]}"
puts "   evaluations: #{counts[:evaluations]}"
puts "   performance: #{counts[:performance]}"
puts "   errors:      #{counts[:errors]}"

# ── Statistics ────────────────────────────────────────────────────────────────

puts "\n4. Statistics (last hour)"
stats = adapter.statistics(time_range: 3600)

dec = stats[:decisions]
puts "   Decisions  — total: #{dec[:total]}, avg confidence: #{dec[:average_confidence].round(3)}, " \
     "success rate: #{(dec[:success_rate] * 100).round(1)}%"

perf = stats[:performance]
puts "   Performance — total: #{perf[:total]}, avg: #{perf[:average_duration_ms].round(2)} ms, " \
     "p95: #{perf[:p95].round(2)} ms"

err = stats[:errors]
puts "   Errors      — total: #{err[:total]}, critical: #{err[:critical_count]}, " \
     "by type: #{err[:by_type]}"

# ── Time series ───────────────────────────────────────────────────────────────

puts "\n5. Time series (60-second buckets, last hour)"
series = adapter.time_series(:decisions, bucket_size: 60, time_range: 3600)
puts "   #{series[:data].length} bucket(s), total decisions in series: #{series[:data].sum.to_i}"

# ── Cleanup ───────────────────────────────────────────────────────────────────

puts "\n6. Cleanup — inserting aged records and running cleanup"

# Manually back-date some records to simulate old data
cutoff = Time.now - (8 * 24 * 3600) # 8 days ago
DecisionLog.limit(3).update_all(created_at: cutoff, updated_at: cutoff)

before = adapter.metrics_count[:decisions]
removed = adapter.cleanup(older_than: 7 * 24 * 3600) # retain 7 days
after  = adapter.metrics_count[:decisions]

puts "   Removed #{removed} records older than 7 days"
puts "   Decisions before: #{before}, after: #{after}"

puts "\n" + "=" * 60
puts "Example complete."
